[project]
name = "baza-filmow-full"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.2",
    "jsonschema>=4.26.0",
    "peewee>=3.19.0",
    "uvicorn>=0.40.0",
]
